### ISSUE TITLE
フリーワード検索機能が欲しい

### ISSUE THREAD

**Issue by huideyeren** [ftnext/diy-proposal-review#47]
現状フリーワードで絞り込める機能がないので、特定の話題を追いたいときにURLをSlackで共有しないといけないのがちょっと不便です。
フリーワードで絞り込みできる機能があると助かります。

**Comment by ftnext** [comment]
フィードバックありがとうございます。
#52 にてタイトルに含む語でand検索できるようにしました。

手短に対応できたのでこのIssueはクローズしますが、
検索機能について要望があればこのIssueを再オープンして要件をお知らせください
